### ISSUE TITLE
Add "--wrap" type option

### ISSUE THREAD

**Issue by mithro** [antmicro/tuttest#10]
Frequently you want to run the commands inside a docker container but you don't want to install tuttest inside the docker container. It would be good if `tuttest` had a `--wrap` or `--prefix` type option which would prefix / run the commands with the option.

For example;
```
tuttest --wrap "docker run --abc 1234" XYZ
```
Would prefix all the commands with `docker run --abc 1234`.

**Comment by mithro** [comment]
@mgielda - This should probably be assigned to @kamilrakoczy so he can finish https://github.com/SymbiFlow/symbiflow-examples/pull/46

**Comment by mgielda** [comment]
I actually added a variant of this functionality some time ago within https://github.com/antmicro/tuttest/blob/master/bin/tuttest, where using +something will prepend the next snippet to be executed with a command, but this has *not* been battle tested ;-)

also this prefixes the entire snippet, whereas I assume you mean to prefix each command with something.

So concluding, I think we could add the ``--prefix-lines-with`` option (I would prefer a more descriptive name here to explain what it does) which does exactly what you need.

**Comment by mgielda** [comment]
@kgugala please assign as needed. Also, please implement what best fits the practical use cases, such as SF's documentation ;-) 'cos my discussion here is purely theoretical, and I'd rather tuttest made sense for real users.
